# Generated by Django 5.1.2 on 2024-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreFruta', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
